blank_issues_enabled: false
contact_links:
  - name: Public \#Klippain thread in the Voron Discord
    url: https://discord.com/channels/460117602945990666/1096701708643614820
    about: Quickest way to get in contact if you just want to have a chat
